travis:
  secure:
    BINSTAR_TOKEN: Dj7GjkkiZNSs0SbdEuLX3aAzkp/OWd49mOdlshwFLnqsq+lMY+ezUDqS8UD5g1ceeQChDb8Zu1RPrirKlMWEjYJzzdseTlOY37GpFKl/YWpt/din0KWY8mpnUAejylGuZ44eqWFm58WMdM6JQQwtAG9elVZDDRnRQyFBjDu/C8WkY9+jv9TLrfzZCMJrOKUOonBZQ4xLT/qYjxkHWvi03nl6XnAkL3XCv53BHrqv1JLkNI8GdGoDSAs5N/Wp9pVNvwB5RfUq3CK7creziRSwXPle2ODE3jU9TgmLiZw5vWpozkGhiZwxTm8nAXUbj3XGnxCFPy+dvf5gGFXSBVFFBqbkT7J+Afr5ghZBCrZC/Zr2QtERfFEGeixW6NPCvbmtj5ydnDXEaIm7UpFZHQk0xJAZoemeM8hvBGjiYmAX5HJMTcAwagg/LDfDQuw8yJsTeKnwu/LIJCpSMDzaGoQ50VWblXKCgIocefn056eFfBkJhsRJ/hPbZxK/xbEg/sEFSk+kyzJ1dlZX1NpM+rlQRR1vhj2oScKqZ0vP5G8qfXBCgeLLF3hF2mNHd7jyf2leNI9lvt9L6ZoM+I0A+sfgsy1ifDXtrFHfZXr98w0vLj9QiBYuB51NYwvAJ6yVuWYtygjo+hhTgh7G61Z5Bcu625LlGXThmQyD0EZHZ6UmuO0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
